### ISSUE TITLE
Update uuids to use aips-0-0-10 everywhere, except old release

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/AirInterfacePowerSaver#127]
serviceList doesn't have an oldRelease http client, but instead it's called AirInterfacePowerSaver with releaseNumber = 0.0.5; there the number is kept!

=> the uuid has the or (with num 005)
aips-0-0-10-op-c-bm-or-0-0-5-000

```
  - http-client:
      application-name: AirInterfacePowerSaver
      release-number: 0.0.5
      uuid: aips-0-0-10-http-c-or-0-0-5-000    # changed
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 4007
      uuid: aips-0-0-10-tcp-c-or-0-0-5-000 # changed
    operation-clients:
      own-oam:
        basic:
          - operation-name: /v1/bequeath-your-data-and-die
            uuid: aips-0-0-10-op-c-bm-or-0-0-5-000 # changed
        individual:
      service:
        basic:
        individual:

  - http-client:
      application-name: NewRelease
      release-number: 0.0.10
      uuid: aips-0-0-10-http-c-nr-0-0-9-000 # previously -> will be changed
    tcp-client:
      remote-protocol: http
      ip-address: 127.0.0.1
      tcp-port: 4017
      uuid: aips-0-0-10-tcp-c-nr-0-0-5-000 # previously -> will be changed
```
