### ISSUE TITLE
Clarification regarding the status-of-link attribute in the callbacks.response of the /v1/switch-redundant-transmitter-pair-off API

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AirInterfacePowerSaver#77]
A small clarification required in the following , 

one of the callback of the API /v1/switch-redundant-transmitter-pair-off is RequestForSwitchingRedundantTransmitterPairOffInitiatesTransaction.Response.
In this callback , we have the following condition defined in the description of the requestBody attribute status-of-link.

```
if NOT ( 
({/v1/receive-transmitter-status-of-parallel-links#parallel-link-list} >= 2 entries)
AND 
(for both link endpoints of at least 1 Link different from the initial Link ( ({/v1/receive-transmitter-status-of-parallel-links#parallel-link-list/transmitter-status-list/interface-status}=="UP") AND ({/v1/receive-transmitter-status-of-parallel-links#parallel-link-list/transmitter-status-list/transmission-mode-cur}=={/v1/receive-transmitter-status-of-parallel-links#parallel-link-list/transmitter-status-list/transmission-mode-max}) ) )
return status-of-link=NotQualified and exit
```

For example , there is a link-id-A , for which we received the following 2 parallel link information , 

```
                   - link-id: 'link-id-A'
                      transmitter-status-list:
                        - interface-status: 'INTERFACE_STATUS_TYPE_UP'
                          transmission-mode-max: '0007-128QAM-78528/87570-1'
                          transmission-mode-cur: '0007-128QAM-78528/87570-1'
                        - interface-status: 'INTERFACE_STATUS_TYPE_UP'
                          transmission-mode-max: '0007-128QAM-78528/87570-1'
                          transmission-mode-cur: '0007-128QAM-78528/87570-1'
                   - link-id: 'link-id-B'
                      transmitter-status-list:
                        - interface-status: 'INTERFACE_STATUS_TYPE_UP'           // link-id-B-endpoint-1
                          transmission-mode-max: '0007-128QAM-78528/87570-1'
                          transmission-mode-cur: '0007-128QAM-78528/87570-1'
                        - interface-status: 'INTERFACE_STATUS_TYPE_UP'         // link-id-B-endpoint-2
                          transmission-mode-max: '0007-128QAM-78528/87570-1'
                          transmission-mode-cur: '0007-128QAM-78528/87570-1'
```

Kindly please let us know whether , 
- We have to check the transmission-mode-cur and transmission-mode-max within the same endpoint. For example link-id-B-endpoint-1/transmission-mode-cur == link-id-B-endpoint-1/transmission-mode-max
**Or**
- whether we have to check the transmission-mode-cur of the endpoints in 'link-id-A' with transmission-mode-max of the endpoints in “link-id-B”
